# Generated by Django 2.2.6 on 2020-07-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200701_2122'),
        ('cart', '0002_mycart_total'),
    ]

    operations = [
    ]
