# Generated by Django 2.2.6 on 2020-07-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_merge_20200701_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='total',
        ),
    ]
