# Generated by Django 2.2.6 on 2020-07-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_mycart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
