# Generated by Django 2.2.6 on 2020-07-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_mycart_size_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
