# Generated by Django 2.2.6 on 2020-06-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SH', 'SHOES'), ('JE', 'JEANS'), ('TP', 'TOP')], default='SH', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField()),
                ('image_url', models.URLField(default='none')),
                ('best_info', models.BooleanField(default=True)),
            ],
        ),
    ]
